
const chatDetails = [
  {
    "id": 1,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Hey mate!",
    "messageNo": 1,
  },
  {
    "id": 2,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "How are you doing?",
    "messageNo": 3,
  },
  {
    "id": 3,
    "isMe": true,
    "profile": "",
    "message": "Hi!",
    "messageNo": 1,
  },
  {
    "id": 4,
    "isMe": true,
    "profile": "",
    "message": "Fine.",
    "messageNo": 2,
  },
  {
    "id": 5,
    "isMe": true,
    "profile": "",
    "message": "Tngai mon khernh u tv aeon2",
    "messageNo": 3,
  },
  {
    "id": 6,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Nhuii mix min hav pg",
    "messageNo": 0,
  },
  {
    "id": 6,
    "isMe": true,
    "profile": "",
    "message": "Eng hav ter tae yg tver min lir ey na",
    "messageNo": 1,
  },
  {
    "id": 6,
    "isMe": true,
    "profile": "",
    "message": "😒😒😒",
    "messageNo": 3,
  },
  {
    "id": 7,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Tv oy ke somtos",
    "messageNo": 1,
  },
  {
    "id": 8,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Lv nv na c ey ot?",
    "messageNo": 3,
  },
  {
    "id": 9,
    "isMe": true,
    "profile": "",
    "message": "Tos",
    "messageNo": 1,
  },
  {
    "id": 10,
    "isMe": true,
    "profile": "",
    "message": "C nv na?",
    "messageNo": 3,
  },
  {
    "id": 11,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Bunchon IFL?",
    "messageNo": 0,
  },
  {
    "id": 12,
    "isMe": true,
    "profile": "",
    "message": "Okay",
    "messageNo": 0,
  },
];